<a href="https://colab.research.google.com/github/surajsharma/learning_tensorflow/blob/main/00_tf_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to tensors

### Creating constant tensors

In [ ]:
# import TF
import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [ ]:
vector = tf.constant([100,100])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([100, 100], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10,7],[3.,2.], [4.,4.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 4.,  4.]], dtype=float32)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

  ### Creating tensors with `tf.Variable`

In [ ]:
changeable_tensor = tf.Variable([10,10])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(4)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 4, 10], dtype=int32)>

### Creating random tensors / shuffle

In [ ]:
r1 = tf.random.Generator.from_seed(42)
r1 = r1.normal(shape=(3,2))


r2 = tf.random.Generator.from_seed(44)
r2 = r2.normal(shape=(3,2))

r1, r2, r1 == r2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7535805 , -0.57166284],
        [ 0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
### Shuffle a tensor when inherent order doesn't matter
not_shuffled = tf.constant([[1,2],[3,4],[5,6], [7,8]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [7, 8],
       [5, 6],
       [3, 4]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed=42) #op level random seed

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 4],
       [7, 8],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) #global random seed
tf.random.shuffle(not_shuffled, seed=42) #op level random seed

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2],
       [7, 8]], dtype=int32)>

In [ ]:
tf.ones([4,4]) #ones

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([3,3]) #zeros

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays to tensors
Tensors can be run on GPUs much faster

In [ ]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_A, shape=(2,3,4))
B=tf.constant(numpy_A)
A, B, A.ndim, B.ndim


(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 3,
 1)

 ### Tensor Attributes
 * Shape `tensor.shape`
 * Rank `tensor.ndim`
 * Axis/Dimension `tensor[0], tensor[:1]`
 * size `tf.size`

In [ ]:
# Create a rank for tensor (4 Dimensions)

rank_4_tensor= tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor

print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor (Numpy): ", tf.size(rank_4_tensor).numpy())


Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor (Numpy):  120


### Indexing tensors

Tensors can be indexed like python lists

In [ ]:
# get first two elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element from each dimension except the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[2,1],[3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# get the last item of each of our rank 12 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [ ]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [1]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
#alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [1]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[2, 1]],

       [[3, 4]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 1],
       [3, 4]], dtype=int32)>

### Tensor Operations

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7], [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor #original tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>